version: "3"
services:
  db:
    image: mysql
    container_name: "sqlrunner_db"
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=sqlrundb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
    volumes:
      - ./data:/var/lib/mysql

  sqlrunner:
    build:
      context: .
    depends_on: 
      - "db"
    ports: 
      - "5000:5000"
    environment:
      - DB_HOST=sqlrunner_db
      - DB_PORT=3306
      - DB_USERNAME=testuser
      - DB_PASSWORD=testpassword
      - DB_NAME=sqlrundb
      - FLASK_ENV=development

  



        

                